name: ðŸ§ Linux Builds
on: [push, pull_request]

# Global Settings
env:
  # Only used for the cache key. Increment version to force clean build.
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=extra werror=yes module_text_server_fb_enabled=yes
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  EM_VERSION: 3.1.18
  EM_CACHE_FOLDER: "emsdk-cache"

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-deploy
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: "ubuntu-20.04"
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Editor Linux (target=editor)
            cache-name: linux-editor
            target: editor
            tests: false
            sconsflags: use_llvm=yes custom_modules=../vsk_modules precision=double linker=gold deprecate=no
            doc-test: false
            bin: "./bin/godot.linuxbsd.editor.double.x86_64.llvm"
            proj-conv: false
            artifact: true
            platform: linuxbsd

          - name: Editor Linux Libgodot (target=editor)
            cache-name: linux-editor-shared-library
            target: editor
            tests: false
            sconsflags: use_llvm=yes custom_modules=../vsk_modules precision=double linker=gold deprecate=no library_type=shared_library
            doc-test: false
            bin: "./bin/libgodot.linuxbsd.editor.double.x86_64.llvm.so"
            proj-conv: false
            artifact: true
            platform: linuxbsd

          - name: Editor Windows (target=editor)
            cache-name: windows-editor
            target: editor
            tests: false
            sconsflags: use_llvm=yes use_mingw=yes custom_modules=../vsk_modules precision=double deprecate=no
            doc-test: false
            bin: "./bin/godot.windows.editor.double.x86_64.llvm.exe"
            proj-conv: false
            artifact: true
            platform: windows

          - name: Editor Windows Libgodot (target=editor)
            cache-name: windows-editor-shared-library
            target: editor
            tests: false
            sconsflags: use_llvm=yes use_mingw=yes custom_modules=../vsk_modules precision=double linker=gold deprecate=no library_type=shared_library
            doc-test: false
            bin: "./bin/godot.windows.editor.double.x86_64.llvm.dll"
            proj-conv: false
            artifact: true
            platform: windows

          # - name: Editor with doubles and GCC sanitizers (target=editor, tests=yes, dev_build=yes, precision=double, use_asan=yes, use_ubsan=yes, linker=gold)
          #   cache-name: linux-editor-double-sanitizers
          #   target: editor
          #   tests: false
          #   sconsflags: dev_build=yes precision=double use_asan=yes use_ubsan=yes linker=gold
          #   proj-test: false
          #   # Can be turned off for PRs that intentionally break compat with godot-cpp,
          #   # until both the upstream PR and the matching godot-cpp changes are merged.
          #   godot-cpp-test: false
          #   bin: "./bin/godot.linuxbsd.editor.dev.double.x86_64.san"
          #   build-mono: false
          #   # Skip 2GiB artifact speeding up action.
          #   artifact: false
          #   platform: linuxbsd
          #
          # - name: Editor with clang sanitizers (target=editor, tests=yes, dev_build=yes, use_asan=yes, use_ubsan=yes, use_llvm=yes, linker=gold)
          #   cache-name: linux-editor-llvm-sanitizers
          #   target: editor
          #   tests: false
          #   sconsflags: dev_build=yes use_asan=yes use_ubsan=yes use_llvm=yes linker=gold
          #   bin: "./bin/godot.linuxbsd.editor.dev.x86_64.llvm.san"
          #   build-mono: false
          #   # Skip 2GiB artifact speeding up action.
          #   artifact: false
          #   platform: linuxbsd

          - name: Web Template (target=template_release)
            cache-name: web-template
            target: template_release
            tests: false
            sconsflags: use_llvm=yes use_mingw=yes custom_modules=../vsk_modules precision=double deprecate=no
            artifact: true
            platform: web

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: clayjohn/tps-demo
          path: tps-demo
          ref: menu

      - name: Move to the root
        run: |
          cp -rf tps-demo/* .
          rm -rf tps-demo

      # Need newer mesa for lavapipe to work properly.
      - name: Linux dependencies for tests
        if: ${{ matrix.proj-test }}
        run: |
          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
          sudo add-apt-repository ppa:kisak/kisak-mesa
          sudo apt-get install -qq mesa-vulkan-drivers binutils

      - name: Linux dependencies for gold linker
        run: |
          sudo apt-get install -qq binutils

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Set up Emscripten latest
        if: ${{ matrix.platform == 'web' }}
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - name: Verify Emscripten setup
        if: ${{ matrix.platform == 'web' }}
        run: |
          emcc -v

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Set up .NET Sdk
        uses: actions/setup-dotnet@v2
        if: ${{ matrix.build-mono }}
        with:
          dotnet-version: "6.0.x"

      - name: Setup GCC problem matcher
        uses: ammaraskar/gcc-problem-matcher@master

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
          platform: ${{ matrix.platform }}
          target: ${{ matrix.target }}
          tests: ${{ matrix.tests }}

      - name: Generate C# glue
        if: ${{ matrix.build-mono }}
        run: |
          ./godot/${{ matrix.bin }} --headless --generate-mono-glue ./godot/modules/mono/glue || true

      - name: Build .NET solutions
        if: ${{ matrix.build-mono }}
        run: |
          ./godot/modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./godot/bin --godot-platform=linuxbsd

      # Execute unit tests for the editor
      - name: Unit tests
        if: ${{ matrix.tests }}
        run: |
          ./godot/${{ matrix.bin }} --version
          ./godot/${{ matrix.bin }} --help
          ./godot/${{ matrix.bin }} --test --headless

      # Check class reference
      - name: Check for class reference updates
        if: ${{ matrix.doc-test }}
        run: |
          echo "Running --doctool to see if this changes the public API without updating the documentation."
          echo -e "If a diff is shown, it means that your code/doc changes are incomplete and you should update the class reference with --doctool.\n\n"
          ./godot/${{ matrix.bin }} --doctool --headless 2>&1 > /dev/null || true
          git diff --color --exit-code && ! git ls-files --others --exclude-standard | sed -e 's/^/New doc file missing in PR: /' | grep 'xml$'

      # Test 3.x -> 4.x project converter
      - name: Test project converter
        if: ${{ matrix.proj-conv }}
        run: |
          mkdir converter_test
          cd converter_test
          touch project.godot
          ../godot/${{ matrix.bin }} --headless --validate-conversion-3to4
          cd ..
          rm converter_test -rf

      # Download and extract zip archive with project, folder is renamed to be able to easy change used project
      - name: Download test project
        if: ${{ matrix.proj-test }}
        run: |
          wget https://github.com/godotengine/regression-test-project/archive/4.0.zip
          unzip 4.0.zip
          mv "regression-test-project-4.0" "test_project"

      # Editor is quite complicated piece of software, so it is easy to introduce bug here
      - name: Open and close editor (Vulkan)
        if: ${{ matrix.proj-test }}
        run: |
          xvfb-run ./godot/${{ matrix.bin }} --audio-driver Dummy --editor --quit --path test_project 2>&1 | tee sanitizers_log.txt || true
          misc/scripts/check_ci_log.py sanitizers_log.txt

      - name: Open and close editor (GLES3)
        if: ${{ matrix.proj-test }}
        run: |
          DRI_PRIME=0 xvfb-run ./godot/${{ matrix.bin }} --audio-driver Dummy --rendering-driver opengl3 --editor --quit --path test_project 2>&1 | tee sanitizers_log.txt || true
          misc/scripts/check_ci_log.py sanitizers_log.txt

      # Run test project
      - name: Run project
        if: ${{ matrix.proj-test }}
        run: |
          xvfb-run ./godot/${{ matrix.bin }} 40 --audio-driver Dummy --path test_project 2>&1 | tee sanitizers_log.txt || true
          misc/scripts/check_ci_log.py sanitizers_log.txt

      # Checkout godot-cpp
      - name: Checkout godot-cpp
        if: ${{ matrix.godot-cpp-test }}
        uses: actions/checkout@v3
        with:
          repository: godotengine/godot-cpp
          submodules: "recursive"
          path: "godot-cpp"

      # Dump GDExtension interface and API
      - name: Dump GDExtension interface and API for godot-cpp build
        if: ${{ matrix.godot-cpp-test }}
        run: |
          ./godot/${{ matrix.bin }} --headless --dump-gdextension-interface --dump-extension-api
          cp -f gdextension_interface.h godot-cpp/gdextension/
          cp -f extension_api.json godot-cpp/gdextension/

      # Build godot-cpp test extension
      - name: Build godot-cpp test extension
        if: ${{ matrix.godot-cpp-test }}
        run: |
          cd godot-cpp/test
          scons target=template_debug dev_build=yes
          cd ../..

      - name: Prepare artifact
        if: ${{ matrix.artifact }}
        run: |
          chmod +x godot/bin/godot.* || true
          chmod +x godot/bin/libgodot.* || true

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        if: ${{ matrix.artifact }}
        with:
          name: ${{ matrix.cache-name }}

  deploy-packages-linux:
    needs: [build-linux]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Download linux-editor artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: vsk_builds.yml
          workflow_conclusion: success
          name: linux-editor

      - name: Download linux-editor-shared-library artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: vsk_builds.yml
          workflow_conclusion: success
          name: linux-editor-shared-library

      - name: Export Linux v-sekai-game
        run: |
          mkdir -p .godot/editor .godot/imported export_linuxbsd
          cp godot.linuxbsd.editor.double.x86_64.llvm reproduction_case_linux.x86_64
          chmod +x godot.linuxbsd.editor.double.x86_64.llvm
          ./godot.linuxbsd.editor.double.x86_64.llvm --headless --xr-mode off --export-pack Linux  `pwd`/reproduction_case_linux.x86_64.pck --path .
          ./godot.linuxbsd.editor.double.x86_64.llvm --headless --xr-mode off --dump-extension-api --dump-gdextension-interface

      - name: Upload Godot Artifact Export Linux
        uses: actions/upload-artifact@v3
        with:
          name: reproduction_case_game_linux_x86_64
          path: |
            libgodot.linuxbsd.editor.double.x86_64.llvm.so
            reproduction_case_linux.x86_64
            reproduction_case_linux.x86_64.pck
            extension_api.json
            gdextension_interface.h
          retention-days: 45

      - name: Upload Godot Artifact Export JSON api
        uses: actions/upload-artifact@v3
        with:
          name: v_sekai_gdextension_api
          path: |
            extension_api.json
            gdextension_interface.h
          retention-days: 45

      - name: Prepare artifacts
        run: |
          export TARGET=reproduction-case-linux-x86_64
          mkdir $TARGET
          cp libgodot.linuxbsd.editor.double.x86_64.llvm.so $TARGET/libgodot.linuxbsd.editor.double.x86_64.llvm.so
          cp reproduction_case_linux.x86_64 $TARGET/reproduction_case_linux.x86_64
          cp reproduction_case_linux.x86_64.pck $TARGET/reproduction_case_linux.x86_64.pck
          cp extension_api.json $TARGET/extension_api.json
          cp gdextension_interface.h $TARGET/gdextension_interface.h
          7z a -r $TARGET.zip $TARGET
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: reproduction-case-linux-x86_64.zip

  deploy-packages-windows:
    needs: [build-linux]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Download linux-editor artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: vsk_builds.yml
          workflow_conclusion: success
          name: linux-editor

      - name: Download windows-editor artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: vsk_builds.yml
          workflow_conclusion: success
          name: windows-editor

      - name: Download windows-editor-shared-library artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: vsk_builds.yml
          workflow_conclusion: success
          name: windows-editor-shared-library

      - name: Export Windows Game
        run: |
          mkdir -p .godot/editor .godot/imported export_windows
          cp godot.windows.editor.double.x86_64.llvm.exe reproduction_case_windows_x86_64.exe
          cp libgodot.windows.editor.double.x86_64.llvm.so libgodot.windows.editor.double.x86_64.llvm.dll
          chmod +x godot.linuxbsd.editor.double.x86_64.llvm
          ./godot.linuxbsd.editor.double.x86_64.llvm --headless --xr-mode off --export-pack Windows `pwd`/reproduction_case_windows_x86_64.pck --path .
          ./godot.linuxbsd.editor.double.x86_64.llvm --headless --xr-mode off --dump-extension-api --dump-gdextension-interface

      - name: Upload Godot Artifact Export Windows
        uses: actions/upload-artifact@v3
        with:
          name: reproduction_case_game_windows_x86_64
          path: |
            libgodot.windows.editor.double.x86_64.llvm.dll
            reproduction_case_windows_x86_64.exe
            reproduction_case_windows_x86_64.pck
            extension_api.json
            gdextension_interface.h
          retention-days: 45

      - name: Prepare artifacts
        run: |
          export TARGET=reproduction-case-windows-x86_64
          mkdir $TARGET
          cp libgodot.windows.editor.double.x86_64.llvm.dll $TARGET/libgodot.windows.editor.double.x86_64.llvm.dll
          cp reproduction_case_windows_x86_64.exe $TARGET/reproduction_case_windows_x86_64.exe
          cp reproduction_case_windows_x86_64.pck $TARGET/reproduction_case_windows_x86_64.pck
          cp extension_api.json $TARGET/extension_api.json
          cp gdextension_interface.h $TARGET/gdextension_interface.h
          7z a -r $TARGET.zip $TARGET
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: reproduction-case-windows-x86_64.zip

  # deploy-packages-web:
  #   needs: [build-linux]
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Download linux-editor artifact
  #       uses: dawidd6/action-download-artifact@v2
  #       with:
  #         workflow: vsk_builds.yml
  #         workflow_conclusion: success
  #         name: linux-editor

  #     - name: Download web-template artifact
  #       uses: dawidd6/action-download-artifact@v2
  #       with:
  #         workflow: vsk_builds.yml
  #         workflow_conclusion: success
  #         name: web-template

  #     - name: Export Web Game
  #       run: |
  #         mkdir -p .godot/editor .godot/imported
  #         chmod +x godot.linuxbsd.editor.double.x86_64.llvm
  #         ./godot.linuxbsd.editor.double.x86_64.llvm --headless --xr-mode off --export-pack Web `pwd`/.web_zip/index.pck --path .

  #     - name: Upload Godot Artifact Export Web
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: reproduction_case_game_web_wasm
  #         path: |
  #           .web_zip
  #         retention-days: 45

  #     - name: Prepare artifacts
  #       run: |
  #         export TARGET=reproduction-case-web-wasm
  #         mkdir $TARGET
  #         mv .web_zip/godot.html .web_zip/index.html
  #         cp .web_zip/* $TARGET/
  #         7z a -r $TARGET.zip $TARGET
  #       shell: bash

  #     - name: Release
  #       uses: softprops/action-gh-release@v1
  #       if: startsWith(github.ref, 'refs/tags/')
  #       with:
  #         files: reproduction-case-web-wasm.zip
